#! /bin/bash

# Author : wenxueliu
#
# Reference
#   http://debuginfo.centos.org/7/x86_64/
#   http://debuginfo.centos.org/6/x86_64/
#   http://my.oschina.net/MaTech/blog/639999


# QA:
#        file /usr/lib/debug/usr/lib64/traceevent/plugins/plugin_cfg80211.so.debug from install of kernel-debuginfo-common-x86_64-3.10.0-327.22.2.el7.x86_64 conflicts with file from package kernel-debuginfo-common-x86_64-3.10.0-229.el7.x86_64
#        file /usr/lib/debug/usr/lib64/traceevent/plugins/plugin_function.so.debug from install of kernel-debuginfo-common-x86_64-3.10.0-327.22.2.el7.x86_64 conflicts with file from package kernel-debuginfo-common-x86_64-3.10.0-229.el7.x86_64
#        file /usr/lib/debug/usr/lib64/traceevent/plugins/plugin_hrtimer.so.debug from install of kernel-debuginfo-common-x86_64-3.10.0-327.22.2.el7.x86_64 conflicts with file from package kernel-debuginfo-common-x86_64-3.10.0-229.el7.x86_64
#        file /usr/lib/debug/usr/lib64/traceevent/plugins/plugin_jbd2.so.debug from install of kernel-debuginfo-common-x86_64-3.10.0-327.22.2.el7.x86_64 conflicts with file from package kernel-debuginfo-common-x86_64-3.10.0-229.el7.x86_64
#        file /usr/lib/debug/usr/lib64/traceevent/plugins/plugin_kmem.so.debug from install of kernel-debuginfo-common-x86_64-3.10.0-327.22.2.el7.x86_64 conflicts with file from package kernel-debuginfo-common-x86_64-3.10.0-229.el7.x86_64
#        file /usr/lib/debug/usr/lib64/traceevent/plugins/plugin_kvm.so.debug from install of kernel-debuginfo-common-x86_64-3.10.0-327.22.2.el7.x86_64 conflicts with file from package kernel-debuginfo-common-x86_64-3.10.0-229.el7.x86_64
#        file /usr/lib/debug/usr/lib64/traceevent/plugins/plugin_mac80211.so.debug from install of kernel-debuginfo-common-x86_64-3.10.0-327.22.2.el7.x86_64 conflicts with file from package kernel-debuginfo-common-x86_64-3.10.0-229.el7.x86_64
#        file /usr/lib/debug/usr/lib64/traceevent/plugins/plugin_sched_switch.so.debug from install of kernel-debuginfo-common-x86_64-3.10.0-327.22.2.el7.x86_64 conflicts with file from package kernel-debuginfo-common-x86_64-3.10.0-229.el7.x86_64
#        file /usr/lib/debug/usr/lib64/traceevent/plugins/plugin_scsi.so.debug from install of kernel-debuginfo-common-x86_64-3.10.0-327.22.2.el7.x86_64 conflicts with file from package kernel-debuginfo-common-x86_64-3.10.0-229.el7.x86_64
#        file /usr/lib/debug/usr/lib64/traceevent/plugins/plugin_xen.so.debug from install of kernel-debuginfo-common-x86_64-3.10.0-327.22.2.el7.x86_64 conflicts with file from package kernel-debuginfo-common-x86_64-3.10.0-229.el7.x86_64

# run with rpm -Uvh  instead of rpm -ivh


check_privilege() {
    if [[ $UID != 0 ]]
    then
        INFO " This script neeeds to be run with sudo, like this:"
        echo -e "\n  sudo $0 $*\n"
        exit 1
    fi
}

check_kernel() {

    if [[ ! -f /etc/redhat-release ]]
    then
        echo "sorry, only redhat and centos support now."
        exit 1;
    fi
    local version=`yum info kernel-devel | grep Version | awk '{print $3}'`
    local arch=`yum info kernel-devel | grep Arch | awk '{print $3}'`
    local release=`yum info kernel-devel | grep Release | awk '{print $3}'`
    local kernel_devel=${version}-${release}.${arch}
    if [[ $kernel_devel != `uname -r` ]]; then
        echo "your kernel version is `uname -r`"
        echo "the kernel version you should use is $kernel-devel"
        echo "run with $ yum update and reboot, then run this script"
        exit 1
    fi
}

check_version() {
    if grep "release 6" /etc/redhat-release >> /dev/null;
    then
        os_version=7
    elif grep "release 6" /etc/redhat-release >> /dev/null;
    then
        os_version=6
    else
        echo "unsupport redhat version"
        cat /etc/redhat-release
        exit 1;
    fi
}

check_privilege
check_kernel
check_version

echo "check pass, continue...."

exit 0;

kernel_version=`uname -r`
machine=`uname -m`

wget -c http://debuginfo.centos.org/${os_version}/${machine}/kernel-debug-debuginfo-${kernel_version}.rpm
wget -c http://debuginfo.centos.org/${os_version}/${machine}/kernel-debuginfo-${kernel_version}.rpm
wget -c http://debuginfo.centos.org/${os_version}/${machine}/kernel-debuginfo-common-${machine}-${kernel_version}.rpm

sudo rpm -ivh  kernel-debug-debuginfo-${kernel_version}.rpm kernel-debuginfo-common-${machine}-${kernel_version}.rpm kernel-debuginfo-${kernel_version}.rpm

yum install -y systemtap systemtap-runtime

stap -v -e 'probe vfs.read {printf("read performed\n"); exit()}'
